apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: awx-operator
valuesInline:
  AWX:
    enabled: true
    name: awx-demo
    postgres:
      enabled: false
    spec:
      service_type: ClusterIP
      ingress_type: ingress
      hostname: awx.example.com
      postgres_storage_class: ebs-sc
      postgres_data_volume_init: true
      postgres_init_container_commands: |
        chown 26:0 /var/lib/pgsql/data
        chmod 700 /var/lib/pgsql/data
  # customVolumes:
  #   postgres:
  #     enabled: true
  #     size: 10Gi
  #     accessModes:
  #       - ReadWriteOnce
  #     storageClassName: ebs-sc
  serviceAccount:
    create: true
    name: awx-operator
