apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: robusta
valuesInline:
  clusterName: ec2-aws

  globalConfig:
    cluster_name: ec2-aws
    enable_platform: false
    signing_key: ""
    sinks: []

  
