apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hublle-redirect-http-route
  namespace: gateways
spec:
  parentRefs:
  - name: cluster-gw
    namespace: gateways
  hostnames:
    - "hublle.cluster-hybrid.ddnsfree.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
            port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hublle-https-route
  namespace: gateways
spec:
  parentRefs:
  - name: cluster-gw
    namespace: gateways
    sectionName: web-ls-tls
  hostnames:
    - hublle.cluster-hybrid.ddnsfree.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: hubble-ui 
      port: 80
---
# apiVersion: cilium.io/v2
# kind: CiliumEgressGatewayPolicy
# metadata:
#   name: argocd-egress-via-worker-pub-1
# spec:
#   selectors:
#     - podSelector:
#         matchLabels:
#           app.kubernetes.io/name: argocd-server
#   destinationCIDRs:
#     - 0.0.0.0/0
#   egressGateway:
#     nodeSelector:
#       matchLabels:
#         kubernetes.io/hostname: worker-pub-1
#     egressIP: 10.0.1.100

