apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nlb-service-job
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3b"
    argocd.argoproj.io/depends-on: nginx-ingress-application
spec:
  project: default
  source:
    repoURL: "https://github.com/cpluan/traineeship-helm-charts.git"
    targetRevision: cni/cilium-v2
    path: gateway-elb/jobs/
  destination:
    server: https://kubernetes.default.svc
    namespace: nlb-infra
  syncPolicy:
    automated:
      selfHeal: true
