apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-prd-application
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/
    repoURL: https://github.com/cpluan/traineeship-helm-charts.git
    targetRevision: root-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lb-controller-application
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: aws-lb-controller/
    repoURL: https://github.com/cpluan/traineeship-helm-charts.git
    targetRevision: root-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-application
  namespace: argocd
spec:
  destination:
    namespace: awx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: awx/
    repoURL: https://github.com/cpluan/traineeship-helm-charts.git
    targetRevision: root-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-application
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kube-prometheus-stack/
    repoURL: https://github.com/cpluan/traineeship-helm-charts.git
    targetRevision: root-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
