apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-prd-chart
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/base/
    repoURL: https://github.com/cpluan/traineeship-helm-charts.git
    targetRevision: root-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: web-gw-tls
    port: 1443
    protocol: TLS
    tls:
      mode: Passthrough
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
  - name: argocd-gateway
  rules:
  - backendRefs:
    - name: argocd-prd-server
      port: 443
