apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-prd-chart
  namespace: argocd
spec:
  destination:
    namespace: awx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: awx/base/
    repoURL: https://github.com/cpluan/traineeship-helm-charts.git
    targetRevision: root-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  postgres_storage_class: local-path
  service_annotations: |
    environment: testing
  service_labels: |
    environment: testing
  service_type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: awx-gateway
  namespace: awx
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: awx-http-gw
    port: 2080
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    name: awx-https-gw
    port: 2443
    protocol: HTTPS
    tls:
      certificateRefs:
      - name: awx-tls-secret
      mode: Terminate
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: awx-http-route
  namespace: awx
spec:
  parentRefs:
  - name: awx-gateway
  rules:
  - backendRefs:
    - name: awx-demo-service
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
