apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/gateway.yaml
  - resources/certificate.yaml
  - resources/network-policy.yaml
  - apps/nlb-gw-service.yaml
  - apps/nlb-gw-job.yaml
  - resources/rbac.yaml
  - resources/hubble-route.yaml


