apiVersion: batch/v1
kind: Job
metadata:
  name: patch-nlb-service
  namespace: ingress-nginx
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: patch-service-sa
      restartPolicy: OnFailure
      containers:
        - name: patch-service
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Aguardando o Service ingress-nginx-controller existir..."
              until kubectl get svc ingress-nginx-controller -n ingress-nginx > /dev/null 2>&1; do
                echo "Service ainda não está disponível, aguardando..."
                sleep 5
              done

              echo "Service encontrado! Lendo valores do ConfigMap..."
              EIPS=$(kubectl get configmap aws-data-config -n kube-system -o jsonpath='{.data.nlb_eip_ids}')
              SUBNETS=$(kubectl get configmap aws-data-config -n kube-system -o jsonpath='{.data.public_subnets_ids}')

              echo "Atualizando Service com EIPs: $EIPS e Subnets: $SUBNETS..."
              kubectl patch svc ingress-nginx-controller -n ingress-nginx --type='merge' -p "{
                \"metadata\": {
                  \"annotations\": {
                    \"service.beta.kubernetes.io/aws-load-balancer-eip-allocations\": \"$EIPS\",
                    \"service.beta.kubernetes.io/aws-load-balancer-subnets\": \"$SUBNETS\",
                    \"service.beta.kubernetes.io/aws-load-balancer-type\": \"external\",
                    \"service.beta.kubernetes.io/aws-load-balancer-target-type\": \"ip\",
                    \"service.beta.kubernetes.io/aws-load-balancer-scheme\": \"internet-facing\",
                    \"service.beta.kubernetes.io/aws-load-balancer-proxy-protocol\": \"*\",
                    \"service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout\": \"3600\",
                    \"service.beta.kubernetes.io/aws-load-balancer-healthcheck-port\": \"30033\",
                    \"service.beta.kubernetes.io/aws-load-balancer-healthcheck-path\": \"/healthz\"
                  }
                },
                \"spec\": {
                  \"selector\": {
                    \"app.kubernetes.io/name\": \"ingress-nginx\",
                    \"app.kubernetes.io/component\": \"controller\"
                  }
                }
              }"
