apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: cluster-hybrid.ddnsfree.com-tls
  issuerRef:
    name: dynu
    kind: ClusterIssuer
  commonName: argocd.cluster-hybrid.ddnsfree.com
  dnsNames:
    - argocd.cluster-hybrid.ddnsfree.com
