apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: cluster-gw
      namespace: gateways
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /argocd
    backendRefs:
      - name: argocd-prd-server  
        port: 30443

