apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  gatewayClassName: cilium
  listeners:
  # - protocol: HTTP
  #   port: 1080
  #   name: web-gw
  #   allowedRoutes:
  #     namespaces:
  #       from: All
  - protocol: TLS
    port: 1443
    name: web-gw-tls
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: argocd-gateway
  rules:
  - backendRefs:
      - name: argocd-prd-server  
        port: 443

---
apiVersion: v1
kind: Service
metadata:
  name: argocd-gw-lb
  namespace: argocd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
spec:
  type: LoadBalancer
  selector:
    gateway.networking.k8s.io/gateway-name: argocd-gateway
  ports:
  - name: http
    port: 443
    targetPort: 1443
