apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  gatewayClassName: cilium
  
  listeners:
  - protocol: HTTP
    name: healthz-ls
    port: 30033
    allowedRoutes:
      namespaces:
        from: Same
  # - protocol: HTTP
  #   name: web-ls
  #   port: 1080
  #   hostname: "*.cluster-hybrid.ddnsfree.com"
  #   allowedRoutes:
  #     namespaces:
  #       from: All
  - protocol: TLS
    name: web-ls-tls
    port: 1443
    hostname: "*.cluster-hybrid.ddnsfree.com"
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: cluster-hybrid.ddnsfree.com-tls
    allowedRoutes:
      namespaces:
        from: All
        
---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: redirect-http-to-https
#   namespace: argocd
# spec:
#   parentRefs:
#     - name: argocd-gateway
#       namespace: argocd
#       sectionName: web-ls
#   hostnames:
#     - "argocd.cluster-hybrid.ddnsfree.com"
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#       filters:
#         - type: RequestRedirect
#           requestRedirect:
#             scheme: https
#             port: 443
#             statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: healthcheck-route
  namespace: argocd
spec:
  parentRefs:
    - name: argocd-gateway
      namespace: argocd
      sectionName: healthz-ls
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /healthz
      filters:
        - type: RequestRedirect
          requestRedirect:
            statusCode: 301
            scheme: https
            port: 443
            # scheme: http
            # hostname: example.com
            # path:
            #   replaceFullPath: /ok


---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
  - name: argocd-gateway
    namespace: argocd
    sectionName: web-ls-tls
  hostnames:
    - argocd.cluster-hybrid.ddnsfree.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: argocd-prd-server 
      port: 30080

---
apiVersion: v1
kind: Endpoints
metadata:
  name: argocd-gateway-lb
  namespace: argocd
subsets:
  - addresses:
      - ip: 10.0.1.100  
      - ip: 10.0.2.100  
    ports:
      - port: 1443
        protocol: TCP
        name: ep-ls-tls
      # - port: 1080
      #   protocol: TCP
      #   name: ep-ls
      - port: 30033
        protocol: TCP
        name: ep-healthz
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-gateway-lb
  namespace: argocd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "30033"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 443
    protocol: TCP
    targetPort: 1443
    name: nlb-ls-tls
  # - port: 80
  #   protocol: TCP
  #   targetPort: 1080
  #   name: nlb-ls
  selector: {} 
