apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-redirect-http-route
  namespace: argocd
spec:
  parentRefs:
  - name: cluster-gw
    namespace: gateways
  hostnames:
    - "argocd.cluster-hybrid.ddnsfree.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
            port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-https-route
  namespace: argocd
spec:
  parentRefs:
  - name: cluster-gw
    namespace: gateways
    sectionName: web-ls-tls
  hostnames:
    - argocd.cluster-hybrid.ddnsfree.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: argocd-prd-server 
      port: 30080
---
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: argocd-egress-via-worker-pub-1
spec:
  selectors:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-server
  destinationCIDRs:
    - 0.0.0.0/0
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: worker-pub-1
    egressIP: 10.0.1.100

