apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: gateways
spec:
  parentRefs:
  - name: cluster-gw
    namespace: gateways
  hostnames:
    - argocd.cluster-hybrid.duckdns.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: argocd-prd-server
      namespace: argocd
      port: 30080


