apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: robusta
valuesInline:
  
  globalConfig:
    signing_key: 6e9abe12-0a7b-4bf3-a4d5-7d3c5e7e60cb
    account_id: bba57a70-49f7-4a14-b045-34d90e9ab135
  sinksConfig:
    - discord_sink:
        name: personal_discord_sink
        url: https://discord.com/api/webhooks/1374668767740825721/PmoE1AlOjj_gBRCBRDXnb1gDw_G4fZ5_L5-o5s4rbuOVdOOlU5cKeksnmaVVyGYAT3e6

  isSmallCluster: true

  enableHolmesGPT: true
  holmes:
    additionalEnvVars:
    - name: MODEL
      value: gpt-4.1-nano
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: holmes-secrets
          key: openAiKey