apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/certificate.yaml
  - resources/network-policy.yaml
  # - apps/nlb-ingress-service.yaml
  - apps/nginx-ingress-app.yaml
  # - apps/nlb-ingress-job.yaml
  # - resources/rbac.yaml
  # - apps/hubble-route.yaml


