apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm.yaml
patches:
  - path: values/helm.yaml
  - path: values/helm-resources.yaml
  - path: values/helm-argocd-components.yaml
