apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName cert-manager
releaseName: cert-manager
name: *appName
version: v1.16.2
repo: https://charts.jetstack.io
namespace: cert-manager
includeCRDs: false

valuesInline:
  crds:
    enabled: false
  extraArgs:
    - --leader-election-namespace=cert-manager
    - --enable-certificate-owner-ref=true
