apiVersion: management.cattle.io/v3
description: User can read everything except secrets
displayName: User - ReadOnly
kind: GlobalRole
builtin: true
metadata:
  name: user-ro
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - pods
      - 'pods/logs'
      - namespaces
      - services
      - configmaps
      - deployments
      - ingresses
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - networking.k8s.io
      - discovery.k8s.io
      - io.k8s.api.discovery
    resources:
      - '*'
    verbs:
      - get
  - apiGroups:
    - management.cattle.io
    resources:
      - preferences
    verbs: 
      - '*'
  - apiGroups:
      - management.cattle.io
    resources:
      - settings
      - rancherusernotifications
      - features
      - roletemplates
      - globalroles
      - globalrolebindings
      - authconfigs
      - users
      - nodedrivers
      - principals
      - fleetworkspaces
      - podsecurityadmissionconfigurationtemplates
      - podsecuritypolicytemplates
      - cisbenchmarkversions
      - cisconfigs
      - rkeaddons
      - rkek8sserviceoptions
      - rkek8ssystemimages
    verbs: 
      - get
      - list
      - watch
  - apiGroups:
      - catalog.cattle.io
    resources:
      - clusterrepos
    verbs:
      - get
      - list
      - watch

