apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-prd-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6a"
spec:
  project: default
  source:
    repoURL: "https://github.com/cpluan/traineeship-helm-charts.git"
    targetRevision: cni/cilium-v2
    path: rancher/overlays/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
