apiVersion: batch/v1
kind: Job
metadata:
  name: patch-nlb-service
  namespace: nlb-infra
  annotations:
    argocd.argoproj.io/hook: PostSync 
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: patch-service-sa
      restartPolicy: OnFailure
      ttlSecondsAfterFinished: 60
      containers:
        - name: patch-service
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "[INFO] Aguardando ConfigMap aws-data-config..."
              until kubectl get configmap aws-data-config -n kube-system > /dev/null 2>&1; do
                echo "[INFO] Aguardando ConfigMap..."
                sleep 5
              done

              echo "[INFO] Aguardando o Service cluster-gw-lb..."
              until kubectl get svc cluster-gw-lb -n nlb-infra > /dev/null 2>&1; do
                echo "[INFO] Aguardando Service..."
                sleep 5
              done

              EIPS=$(kubectl get configmap aws-data-config -n kube-system -o jsonpath='{.data.nlb_eip_ids}')
              SUBNETS=$(kubectl get configmap aws-data-config -n kube-system -o jsonpath='{.data.public_subnets_ids}')

              echo "[INFO] Aplicando patch ao Service com EIPs: $EIPS e Subnets: $SUBNETS"

              kubectl patch svc cluster-gw-lb -n nlb-infra --type='merge' -p "{
                \"metadata\": {
                  \"annotations\": {
                    \"service.beta.kubernetes.io/aws-load-balancer-eip-allocations\": \"$EIPS\",
                    \"service.beta.kubernetes.io/aws-load-balancer-subnets\": \"$SUBNETS\",
                    \"service.beta.kubernetes.io/aws-load-balancer-type\": \"external\",
                    \"service.beta.kubernetes.io/aws-load-balancer-target-type\": \"ip\",
                    \"service.beta.kubernetes.io/aws-load-balancer-scheme\": \"internet-facing\",
                    \"service.beta.kubernetes.io/aws-load-balancer-proxy-protocol\": \"*\",
                    \"service.beta.kubernetes.io/aws-load-balancer-healthcheck-port\": \"30033\",
                    \"service.beta.kubernetes.io/aws-load-balancer-healthcheck-path\": \"/healthz\"
                  }
                }
              }"

              echo "[INFO] Patch aplicado com sucesso."
