apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName reflector
name: *appName
repo: https://emberstack.github.io/helm-charts
version: 9.1.4
releaseName: reflector
namespace: reflector
valuesInline:

  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
