apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


generators:
  - helm.yaml

# https://stackoverflow.com/questions/78092144/trying-to-replace-values-yaml-file-for-helm-chart-in-kustomize-overlay
# https://github.com/kubernetes-sigs/kustomize/issues/4658