apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName kube-prometheus-stack
valuesInline:
  
  # Anchor para reaproveitamento
  controlplaneSelector: &controlplane-selector
    node-role.kubernetes.io/control-plane: "true"
  controlplaneTolerations: &controlplane-tolerations
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/etcd"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"

  # Configurações do Prometheus
  prometheus:
    enabled: true
    prometheusSpec:
      replicas: 1
      retention: 15d
      nodeSelector: *controlplane-selector
      tolerations: *controlplane-tolerations
    service:
      type: ClusterIP

  # Configurações do Alertmanager
  alertmanager:
    enabled: true
    alertmanagerSpec:
      replicas: 1
    service:
      type: ClusterIP

  # Configurações do Grafana
  grafana:
    enabled: true
    nodeSelector: *controlplane-selector
    tolerations: *controlplane-tolerations
    env:
      GF_SERVER_ROOT_URL: &gfRootUrl "https://prometheus.cluster-hybrid.ddnsfree.com"
    grafana.ini:
      security:
        cookie_samesite: "none"
        cookie_secure: true
        allow_embedding: true
      server:
        root_url: *gfRootUrl
      auth.anonymous:
        enabled: "true"
        hide_version: "true"
        org_role: "Viewer"
    service:
      type: ClusterIP
 

  # Configurações do Node Exporter
  nodeExporter:
    enabled: true

  # Configurações do Kube State Metrics
  kubeStateMetrics:
    enabled: true

