apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-hybrid.duckdns.org
spec:
  issuerRef:
    name: duckdns
    kind: ClusterIssuer
  secretName: cluster-hybrid.duckdns.org-tls
  commonName: cluster-hybrid.duckdns.org
  dnsNames:
    - cluster-hybrid.duckdns.org
    - '*.cluster-hybrid.duckdns.org'