kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: duckdns
spec:
  acme:
    privateKeySecretRef:
      name: duckdns-duckdns-issuer
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'luanpcrisostomo@gmail.com' 
    solvers:
      - dns01:
          webhook:
            groupName: lego.dns-solver
            solverName: lego-solver
            config:
              # available provider refer to https://go-acme.github.io/lego/dns/#dns-providers
              provider: duckdns
              disablePropagationCheck: true
              envFrom: # use env from secret
                secret:
                  name: duckdns-secret
                  namespace: 'cert-manager'
              # envs: 
              #   DUCKDNS_TOKEN: '431e374c-2cc3-4705-9e4b-82f75857ef7e'