kind: Secret
apiVersion: v1
metadata:
  name: duckdns-secret
  namespace: cert-manager
stringData:
  # The key will be passed to Lego DNS Provider as an credentials
  # ref: https://go-acme.github.io/lego/dns/duckdns/#credentials
  DUCKDNS_TOKEN: '431e374c-2cc3-4705-9e4b-82f75857ef7e'
  DUCKDNS_PROPAGATION_TIMEOUT: "120"
  DUCKDNS_POLLING_INTERVAL: "30"
  DUCKDNS_TTL: "200"
