apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      imagePullSecrets:
          - name: benchmark-pull-secret
      containers:
        - name: iperf-server
          imagePullPolicy: Always
          image: 290115371037.dkr.ecr.eu-west-1.amazonaws.com/iperf3-benchmark:latest
          env:
            - name: SERVER_MODE
              value: "true"
          ports:
            - containerPort: 5201
              protocol: TCP
            - containerPort: 5201
              protocol: UDP