apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-client-test
spec:
  template:
    metadata:
      labels:
        app: iperf-client-test
    spec:
      restartPolicy: Never
      imagePullPolicy: Always
      imagePullSecrets:
          - name: benchmark-pull-secret
      containers:
        - name: iperf-client
          image: 290115371037.dkr.ecr.eu-west-1.amazonaws.com/iperf3-benchmark:20250522-07ec8ea-155338
          env:
            - name: SERVER_IP
              value: "iperf-server"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TEST_TYPE
              value: "tcp"
            - name: TEST_SCALE
              value: "inter"
            - name: TEST_DURATION
              value: "180"
            - name: S3_BUCKET
              value: "ec2-rke2-benchmark-data"

         