apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: awx-operator
name: awx-operator
chartName: awx-operator
repo: https://ansible-community.github.io/awx-operator-helm/
version: 2.19.1
releaseName: awx-operator
namespace: awx

