apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-prd-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8b"
    argocd.argoproj.io/depends-on: rancher-prd-chart

spec:
  project: default
  source:
    repoURL: "https://github.com/cpluan/traineeship-helm-charts.git"
    targetRevision: benchmark/ingress-baremetal
    path: rancher/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
    - group: management.cattle.io
      kind: User
      jsonPointers:
        - /metadata
        - /status
    - group: management.cattle.io
      kind: GlobalRole
      jsonPointers:
        - /metadata
        - /status
    - group: management.cattle.io
      kind: GlobalRoleBinding
      jsonPointers:
        - /metadata
        - /status
