apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-prd-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8a"
spec:
  project: default
  source:
    repoURL: "https://github.com/cpluan/traineeship-helm-charts.git"
    targetRevision: benchmark/ingress-v1
    path: robusta/overlays/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: robusta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
