apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: cert-manager-webhook-ca
  secretName: cert-manager-webhook-ca
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  privateKey:
    rotationPolicy: Always
