apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName cert-manager
releaseName: cert-manager
name: *appName
version: v1.16.2
repo: https://charts.jetstack.io
namespace: kube-system
includeCRDs: false

valuesInline:
  crds:
    enabled: false

  rbac:
    create: true

  config:
    apiVersion: controller.config.cert-manager.io/v1alpha1
    kind: ControllerConfiguration
    enableCertificateOwnerRef: true

