apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName cert-manager
releaseName: cert-manager
name: *appName
version: 1.16.2
repo: https://charts.jetstack.io
namespace: cert-manager
includeCRDs: true
additionalArgs:
  - "--enable-helm"

valuesFile: ../../base/values.yaml




