apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName ingress-nginx
name: *appName
repo: https://kubernetes.github.io/ingress-nginx
version: 4.10.1
releaseName: ingress-nginx
namespace: ingress-nginx
valuesInline:
  controller:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    nodeSelector:
      egress-node: "true"
    
    tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Equal"
        value: "egress"
        effect: "NoSchedule"

    replicaCount: 2

    service:
      enabled: false

    # config:
    #   use-proxy-protocol: "true"
    #   real-ip-header: "proxy_protocol"
    #   use-forwarded-headers: "true"
    #   log-format-upstream: >
    #     $proxy_protocol_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"



    
