apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName ingress-nginx
name: *appName
repo: https://kubernetes.github.io/ingress-nginx
version: 4.10.1
releaseName: ingress-nginx
namespace: ingress-nginx
valuesInline:
  controller:
    nodeSelector:
      egress-node: "true"
    
    tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Equal"
        value: "egress"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/egress"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

    replicaCount: 2

    service:
      enabled: false

    # hostNetwork: true 
    # dnsPolicy: ClusterFirstWithHostNet
    config:
      whitelist-source-range: |
        185.98.249.5/32,
        87.196.73.90/32,
        62.28.213.98/32,
        10.0.0.0/16
      use-proxy-protocol: "true"
      real-ip-header: "proxy_protocol"
      use-forwarded-headers: "true"
      log-format-upstream: >
        $proxy_protocol_addr - $remote_user [$time_local]
        "$request" $status $body_bytes_sent
        "$http_referer" "$http_user_agent"
        "$request_length" "$request_time" "$upstream_response_time"
        "$upstream_addr" "$upstream_status" "$upstream_bytes_sent"
        "$host" "$server_name" "$scheme" "$http_x_forwarded_for"
        "$http_x_forwarded_proto" "$http_x_forwarded_host" "$request_uri"


    
