apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName ingress-nginx
name: *appName
repo: https://kubernetes.github.io/ingress-nginx
version: 4.10.1
releaseName: ingress-nginx
namespace: ingress-nginx
valuesInline:
  controller:
    replicaCount: 2

    service:
      type: LoadBalancer
      targetPorts:
          http: http
          https: http
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-0d810c00ffbb11329, eipalloc-03150e91a911e02ad"
        service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-05551d250c615a055, subnet-0c54e3b9c8df25bef"
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"

    config:
      use-proxy-protocol: "true"
      real-ip-header: "proxy_protocol"
      use-forwarded-headers: "true"


    
