apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lb-controller-chart
  namespace: kube-system
spec:
  project: system
  source:
    repoURL: 'https://github.com/cpluan/traineeship-helm-charts.git'
    targetRevision: HEAD
    path: aws-lb-controller/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
