apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - helm

patches:
  - target:
      version: v1
      kind: Deployment
      name: aws-load-balancer-controller
      namespace: kube-system
    path: patch-deployment.json