apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName cert-manager-lego-webhook
releaseName: cert-manager-lego-webhook
name: *appName
version: 1.2.0
repo: https://yxwuxuanl.github.io/cert-manager-lego-webhook/
namespace: cert-manager

valuesInline:
  # Some nameserver not responding
  # https://intodns.com/duckdns.org
  # https://go-acme.github.io/lego/usage/cli/options/index.html
  # https://github.com/go-acme/lego/discussions/2244#discussioncomment-11008783
  # webhook:
  #   extraArgs: ["--dns.propagation-disable-ans"]
  crds:
    enabled: true
  certManager:
    namespace: 'cert-manager'
    serviceAccountName: cert-manager

