apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName ebs-csi-driver
name: *appName
repo: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
version: 2.28.0 
releaseName: ebs-csi-driver
namespace: kube-system
valuesInline:
  controller:
    serviceAccount:
      create: true
  storageClasses:
    enabled: false

