apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: cluster-hybrid.ddnsfree.com-tls
  issuerRef:
    name: dynu
    kind: ClusterIssuer
  commonName: prometheus.cluster-hybrid.ddnsfree.com
  dnsNames:
    - prometheus.cluster-hybrid.ddnsfree.com
