apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-prd-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/depends-on: argocd/prometheus-stack-prd-crds
    argocd.argoproj.io/sync-wave: "2b"
spec:
  project: default
  source:
    repoURL: 'https://github.com/cpluan/traineeship-helm-charts.git'
    targetRevision: root-applications
    path: kube-prometheus-stack/overlays/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
