apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objstore-config
  namespace: monitoring
data:
  objstore.yml: |
    type: s3
    config:
      bucket: "ec2-rke2-benchmark-data"
      endpoint: "s3.amazonaws.com"
      region: "eu-west-1"
      insecure: false
      iam: true
      prefix: "cluster-thanos/"
