apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: "ec2-rke2-benchmark-data"
      endpoint: "s3.amazonaws.com"
      region: "eu-west-1"
      aws_sdk_auth: true
    prefix: "cluster-thanos/"
