apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName kube-prometheus-stack
valuesInline:
  # Prometheus
  prometheus:
    prometheusSpec:
      resources:
        requests: &prometheusRequests
          cpu: 250m
          memory: 512Mi
        limits:
          <<: *prometheusRequests
          cpu: 500m

  # Alertmanager
  alertmanager:
    alertmanagerSpec:
      resources:
        requests: &alertmanagerRequests
          cpu: 100m
          memory: 256Mi
        limits:
          <<: *alertmanagerRequests
          cpu: 300m

  # Grafana
  grafana:
    resources:
      requests: &grafanaRequests
        cpu: 100m
        memory: 256Mi
      limits:
        <<: *grafanaRequests
        cpu: 300m

  # Node Exporter
  prometheus-node-exporter:
    resources:
      requests: &nodeExporterRequests
        cpu: 50m
        memory: 100Mi
      limits:
        <<: *nodeExporterRequests
        cpu: 150m

  # Kube State Metrics
  kube-state-metrics:
    resources:
      requests: &kubeStateMetricsRequests
        cpu: 50m
        memory: 128Mi
      limits:
        <<: *kubeStateMetricsRequests
        cpu: 200m

  # Regras de alerta personalizadas
  additionalPrometheusRulesMap:
    custom.rules:
      groups:
        - name: custom.rules
          rules:
            - alert: HighPodMemoryUsage
              expr: sum(container_memory_usage_bytes) / sum(machine_memory_bytes) > 0.9
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: "Uso de memória dos pods elevado"
                description: "O uso de memória dos pods excedeu 90% nos últimos 5 minutos."
