apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName kube-prometheus-stack
valuesInline:

  # Configurações do Prometheus
  prometheus:
    enabled: true
    thanosService:
      enabled: true
    thanosServiceMonitor:
      enabled: true

    
    prometheusSpec:
      disableCompaction: true
      replicas: 1
      thanos:
        image: quay.io/thanos/thanos:v0.37.0
        objectStorageConfig:
          existingSecret:
            name: thanos-objstore-secret
            key: objstore.yml
        grpcServerTlsConfig: {}
        listenLocal: false



      # # Habilita Thanos Sidecar
      # thanos:
      #   baseImage: quay.io/thanos/thanos
      #   version: v0.35.1
      #   objectStorageConfig:
      #     existingSecret:
      #       name: thanos-objstore-secret
      #       key: objstore.yml

      # externalLabels:
      #   cluster: "prod-cluster"
      #   replica: "a"

      # Tempo de retenção local curto
      retention: 24h
      additionalArgs:
        - name: storage.tsdb.max-block-duration
          value: 30s
        - name: storage.tsdb.min-block-duration
          value: 30s
      # # Armazenamento local (usado para blocos antes de irem pro S3)
      # storageSpec:
      #   volumeClaimTemplate:
      #     spec:
      #       storageClassName: ebs-sc
      #       accessModes: ["ReadWriteOnce"]
      #       resources:
      #         requests:
      #           storage: 50Gi

      
  
        

  # Configurações do Alertmanager
  alertmanager:
    enabled: true
    alertmanagerSpec:
      replicas: 1

  # Configurações do Grafana
  grafana:
    enabled: true


  # Configurações do Node Exporter
  nodeExporter:
    enabled: true



  # Configurações do Kube State Metrics
  kubeStateMetrics:
    enabled: true

