apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName kube-prometheus-stack
valuesInline:
  # Prometheus
  prometheus:
    prometheusSpec:
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi


  # Alertmanager
  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 300m
          memory: 512Mi


  # Grafana
  grafana:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi


  # Node Exporter
  prometheus-node-exporter:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 150m
        memory: 200Mi


  # Kube State Metrics
  kube-state-metrics:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  prometheusOperator:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi

  prometheusConfigReloader:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi



  # Regras de alerta personalizadas
  additionalPrometheusRulesMap:
    custom.rules:
      groups:
        - name: custom.rules
          rules:
            - alert: HighPodMemoryUsage
              expr: sum(container_memory_usage_bytes) / sum(machine_memory_bytes) > 0.9
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: "Uso de memória dos pods elevado"
                description: "O uso de memória dos pods excedeu 90% nos últimos 5 minutos."
