apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName kube-prometheus-stack
valuesInline:
  # Prometheus
  prometheus:
    prometheusSpec:
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 300m
          memory: 1Gi


  # Alertmanager
  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 1m
          memory: 50Mi
        limits:
          cpu: 5m
          memory: 50Mi


  # Grafana
  grafana:
    resources:
      requests:
        cpu: 5m
        memory: 100Mi
      limits:
        cpu: 15m
        memory: 100Mi     
    sidecar:
      resources:
        requests:
          cpu: 5m
          memory: 100Mi
        limits:
          cpu: 15m
          memory: 100Mi
      


  # Node Exporter
  prometheus-node-exporter:
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        cpu: 10m
        memory: 10Mi


  # Kube State Metrics
  kube-state-metrics:
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 150m
        memory: 200Mi

  prometheusOperator:
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 150m
        memory: 200Mi

  prometheusConfigReloader:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 150m
        memory: 100Mi

  # Recursos do webhook
  webhook:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi

   # Recursos do fleet (controller, agent, gitjob)
  fleet:
    controller:
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 512Mi
    agent:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi
    gitjob:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi

  # Regras de alerta personalizadas
  additionalPrometheusRulesMap:
    custom.rules:
      groups:
        - name: custom.rules
          rules:
            - alert: HighPodMemoryUsage
              expr: sum(container_memory_usage_bytes) / sum(machine_memory_bytes) > 0.9
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: "Uso de memória dos pods elevado"
                description: "O uso de memória dos pods excedeu 90% nos últimos 5 minutos."
