apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName kube-prometheus-stack
valuesInline: 

  # Configurações do Prometheus
  prometheus:
    enabled: true
    thanosService:
      enabled: true
    thanosServiceMonitor:
      enabled: true

    
    prometheusSpec:
      retention: '24h'
      disableCompaction: true
      replicas: 1
      thanos:
        blockSize: 30s
        image: quay.io/thanos/thanos:v0.37.0
        objectStorageConfig:
          existingSecret:
            name: thanos-objstore-secret
            key: objstore.yml
        grpcServerTlsConfig: {}
        listenLocal: false


      

  # Configurações do Alertmanager
  alertmanager:
    enabled: true
    alertmanagerSpec:
      replicas: 1

  # Configurações do Grafana
  grafana:
    enabled: true


  # Configurações do Node Exporter
  nodeExporter:
    enabled: true



  # Configurações do Kube State Metrics
  kubeStateMetrics:
    enabled: true

