apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: thanos-sidecar
valuesInline:
  existingObjstoreSecret: thanos-objstore-secret
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      default:
        absent_rules: true
        store_gateway: true
        compaction: true
        query: true

  compactor:
    enabled: true
    logLevel: debug
    persistence:
      size: 50Gi
      storageClass: ebs-sc

  storegateway:
    logLevel: debug
    enabled: true
    persistence:
      size: 10Gi
      storageClass: ebs-sc
  
  query:
    enabled: true
    replicaLabel:
      - replica
    logLevel: debug
    dnsDiscovery:
      enabled: false
    stores:
      - prometheus-operated.monitoring.svc.cluster.local:10901
    extraFlags:
      - --store=prometheus-operated.monitoring.svc.cluster.local:10901
  service:
    type: ClusterIP
    port: 10902
  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true
  podSecurityContext:
    fsGroup: 1000
