apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cpluan/traineeship-helm-charts.git'
    targetRevision: root-applications 
    path: awx/
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
