apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cluster-gw
  namespace: nlb-infra
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 1080
    hostname: "*.cluster-hybrid.ddnsfree.com"
    name: web-ls
    allowedRoutes:
      namespaces:
        from: All
  - protocol: TLS
    port: 1443
    hostname: "*.cluster-hybrid.ddnsfree.com"
    name: web-ls-tls
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: cluster-hybrid.ddnsfree.com-tls
    allowedRoutes:
      namespaces:
        from: All

