apiVersion: batch/v1
kind: Job
metadata:
  name: patch-nlb-service
  namespace: gateways
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: patch-service-sa
      restartPolicy: OnFailure
      containers:
        - name: patch-service
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Lendo valores do ConfigMap..."
              EIPS=$(kubectl get configmap aws-data-config -n gateways -o jsonpath='{.data.nlb_eip_ids}')
              SUBNETS=$(kubectl get configmap aws-data-config -n gateways -o jsonpath='{.data.public_subnets_ids}')

              echo "Atualizando Service com EIPs: $EIPS e Subnets: $SUBNETS..."
              kubectl patch svc cluster-gw-lb -n gateways --type='merge' -p "{
                \"metadata\": {
                  \"annotations\": {
                    \"service.beta.kubernetes.io/aws-load-balancer-eip-allocations\": \"$EIPS\",
                    \"service.beta.kubernetes.io/aws-load-balancer-subnets\": \"$SUBNETS\"
                  }
                }
              }"
