apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName rancher
valuesInline:
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  agent:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi


  rancherWebhook:
    resources:
      requests: &webhookRequests
        cpu: 100m
        memory: 256Mi
      limits:
        <<: *webhookRequests
        cpu: 200m


  # Cluster API (CAPI) Controller Manager
  clusterProvisioner:
    resources:
      requests: &capiRequests
        cpu: 500m
        memory: 600Mi
      limits:
        <<: *capiRequests
        cpu: 1
        memory: 1200Mi

  certmanager:
    cainjector:
      resources:
        requests: &cainjectorRequests
          cpu: 50m
          memory: 64Mi
        limits:
          <<: *cainjectorRequests
          cpu: 100m
          memory: 128Mi

    webhook:
      resources:
        requests: &certWebhookRequests
          cpu: 50m
          memory: 64Mi
        limits:
          <<: *certWebhookRequests
          cpu: 100m
          memory: 128Mi

    manager:
      resources:
        requests: &certManagerRequests
          cpu: 100m
          memory: 128Mi
        limits:
          <<: *certManagerRequests
          cpu: 200m
          memory: 256Mi


