apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName rancher
valuesInline:
  replicas: 2

  global:
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"







