apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-prd-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3b"
    argocd.argoproj.io/depends-on: external-secrets-prd-chart

spec:
  project: default
  source:
    repoURL: "https://github.com/cpluan/traineeship-helm-charts.git"
    targetRevision: benchmark/ingress-v1
    path: external-secrets/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

