apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: aws-load-balancer-controller
valuesInline:

  controllerConfig:
    # Aqui você pode usar feature gates se quiser, mantive vazio
    featureGates: {}

