apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: robusta
name: robusta
repo: https://robusta-charts.storage.googleapis.com
version: 0.23.0
releaseName: robusta
namespace: robusta
