apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: benchmark-pull-secret
  namespace: benchmark
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: benchmark-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - generatorRef:
        kind: ECRAuthorizationToken
        apiVersion: generators.external-secrets.io/v1alpha1
        name: ecr-token-generator
