apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: benchmark-pull-secret
  namespace: benchmark
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: benchmark-pull-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .ecr-token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-token-generator
