apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth: {}  # ← usa metadados da EC2 (IAM Role)
