apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/cpluan/traineeship-helm-charts.git"
    targetRevision: cni/cilium-v2
    path: ingress-elb/base/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
