apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3a"
spec:
  project: default
  source:
    repoURL: "https://github.com/cpluan/traineeship-helm-charts.git"
    targetRevision: benchmark/ingress-v1
    path: ingress-elb/base/
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
