apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nlb-ingress-hosts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3c"
spec:
  project: default
  source:
    repoURL: "https://github.com/cpluan/traineeship-helm-charts.git"
    targetRevision: cni/calico-v1
    path: ingress-elb/ingress/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
