apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/rbac.yaml
  - resources/certificate.yaml
  - resources/gateway.yaml
  # - resources/network-policy.yaml
  - apps/nlb-routes.yaml
  - apps/nlb-service-job.yaml


