apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName kube-prometheus-stack
releaseName: prometheus-stack
name: *appName
version: 70.1.1
repo: https://prometheus-community.github.io/helm-charts
namespace: monitoring
includeCRDs: true
additionalArgs:
  - "--enable-helm"

# Adicionando API versions para suportar CRDs personalizados do kube-prometheus-stack
apiVersions:
  - monitoring.coreos.com/v1
  - apps/v1
  - batch/v1
  - policy/v1
