apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: aws-ebs-csi-driver
valuesInline:
  node:
    hostNetwork: true
  controller:
    serviceAccount:
      create: true
  storageClasses: [] 

