apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName aws-ebs-csi-driver
name: *appName
repo: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
version: 2.41.0 
releaseName: aws-ebs-csi-driver
namespace: kube-system
valuesInline:
  node:
    hostNetwork: true
  controller:
    serviceAccount:
      create: true
  storageClasses: [] 

