apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &appName aws-ebs-csi-driver
name: *appName
repo: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
version: 2.41.0
releaseName: aws-ebs-csi-driver
namespace: kube-system
valuesInline:
  node:
    resources:
      requests: &nodeRequests
        cpu: 200m
        memory: 256Mi
      limits:
        <<: *nodeRequests
        cpu: 500m
        memory: 256Mi

  controller:
    resources:
      requests: &controllerRequests
        cpu: 200m
        memory: 256Mi
      limits:
        <<: *controllerRequests
        cpu: 500m
        memory: 256Mi


  storageClasses: []
