apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.8
          ports:
            - containerPort: 8086
          env:
            - name: INFLUXDB_DB
              value: iperf
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
        - name: chronograf
          image: chronograf:1.9
          ports:
            - containerPort: 8888
          env:
            - name: INFLUXDB_URL
              value: http://influxdb:8086
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf
spec:
  selector:
    app: chronograf
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
