apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-client-test
spec:
  template:
    metadata:
      labels:
        app: iperf-client-test
    spec:
      restartPolicy: Never
      containers:
        - name: iperf-client
          image: amazonlinux:2023
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e

              dnf install -y --allowerasing curl-full libcurl-full
              dnf install -y awscli jq iperf3

              PROM_URL="http://prometheus-stack-kube-prom-prometheus.monitoring.svc:9090/api/v1/query_range"

              CPU_QUERY='100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance))'
              MEM_QUERY='100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))'
              DISK_QUERY='100 - ((node_filesystem_avail_bytes{mountpoint="/", fstype!="rootfs"} * 100) / node_filesystem_size_bytes{mountpoint="/", fstype!="rootfs"})'

              # Armazenar timestamp de início
              START_TS=$(date +%s)

              iperf3 -c iperf-server -t 900 -J > /tmp/result.json || {
                echo "[ERRO] iperf3 falhou"; exit 1;
              }

              # Timestamp final
              END_TS=$(date +%s)
              STEP="5"  # coleta a cada 15s

              WINDOW=300  # 5 minutos

              collect_range_metric() {
                local query="$1"
                local start_ts="$2"
                local end_ts="$3"
                local result="[]"

                while [ "$start_ts" -lt "$end_ts" ]; do
                  next_ts=$((start_ts + WINDOW))
                  if [ "$next_ts" -gt "$end_ts" ]; then
                    next_ts=$end_ts
                  fi

                  echo "[INFO] Coletando de $start_ts até $next_ts..."
                  resp=$(curl -sfG "$PROM_URL" \
                    --data-urlencode "query=$query" \
                    --data-urlencode "start=$start_ts" \
                    --data-urlencode "end=$next_ts" \
                    --data-urlencode "step=$STEP")

                  # Verifica se retornou dados válidos
                  new_data=$(echo "$resp" | jq '.data.result')
                  if [ "$(echo "$new_data" | jq length)" -gt 0 ]; then
                    result=$(echo "$result + $new_data" | jq -s 'add')
                  fi

                  start_ts=$next_ts
                done

                echo "$result"
              }

              echo "Coletando métricas entre $START_TS e $END_TS..."

              cpu_data=$(collect_range_metric "$CPU_QUERY" "$START_TS" "$END_TS")
              mem_data=$(collect_range_metric "$MEM_QUERY" "$START_TS" "$END_TS")
              disk_data=$(collect_range_metric "$DISK_QUERY" "$START_TS" "$END_TS")
                            
              cat <<EOF > /tmp/metrics.json
              {
                "start": $START_TS,
                "end": $END_TS,
                "cpu": $cpu_data,
                "memory": $mem_data,
                "disk": $disk_data
              }
              EOF

              # Enviar arquivos para o S3
              TS=$(date +%s)
              aws s3 cp /tmp/result.json s3://ec2-rke2-benchmark-data/iperf/inter/result-$TS.json
              aws s3 cp /tmp/metrics.json s3://ec2-rke2-benchmark-data/metrics/iperf-metrics-$TS.json
              aws s3 cp /tmp/result.json s3://ec2-rke2-benchmark-data/tests/iperf/inter/$TS/result-$TS.json
              aws s3 cp /tmp/metrics.json s3://ec2-rke2-benchmark-data/tests/iperf/inter/$TS/metrics-$TS.json

              echo "[OK] Teste finalizado e arquivos enviados"
