apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-client-inter
spec:
  template:
    metadata:
      labels:
        app: iperf-client-inter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: iperf-server
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Never
      containers:
        - name: iperf-client
          image: networkstatic/iperf3
          command: ["iperf3", "-c", "iperf-server", "-t", "10"]