apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-client-inter-db
spec:
  template:
    metadata:
      labels:
        app: iperf-client-inter-db
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: iperf-server
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Never
      containers:
        - name: iperf-client
          image: alpine:3.18
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache iperf3 jq mongodb-tools && \
              iperf3 -c iperf-server -J > /tmp/result.json && \
              mongoimport --uri mongodb://mongo:27017/iperf --collection results --file /tmp/result.json && \
              echo "[OK] JSON enviado para MongoDB"
