apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-client-inter-db
spec:
  template:
    metadata:
      labels:
        app: iperf-client-inter-db
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: iperf-server
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Never
      containers:
        - name: iperf-client
          image: amazonlinux:2023
          command: ["/bin/bash", "-c"]
          args:
            - |
              yum install -y iperf3 jq unzip curl sudo less && \
              curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" && \
              unzip awscliv2.zip && \
              ./aws/install && \
              export PATH=$PATH:/usr/local/bin && \
              TIMESTAMP=$(date +%s) && \
              aws s3 cp /tmp/result.json s3://ec2-rke2-benchmark-data/iperf/result-${TIMESTAMP}.json && \
              echo "[OK] JSON enviado para o S3"
