apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iperf-test

resources:
  - iperf-server.yaml
  - service.yaml
  - mongo.yaml
  # - job-intra.yaml
  # - job-inter.yaml
  - job-inter-db.yaml
  - job-intra-db.yaml
