apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/namespace.yaml
  - https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
  - resources/clusterissuer.yaml

namespace: cert-manager
