apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/cert-manager-chart.yaml
  - apps/cert-manager-lego.yaml
  - apps/cert-manager-selfsigned.yaml
  - apps/cert-manager-reflector.yaml




