apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - resources/cert-manager-ss-crds.yaml
  - resources/cert-manager-ss-chart.yaml
  - resources/cert-manager-ss-resources.yaml



