apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awx.cluster-hybrid.duckdns.org
spec:
  issuerRef:
    name: duckdns
    kind: ClusterIssuer
  secretName: awx.cluster-hybrid.duckdns.org-tls
  commonName: awx.cluster-hybrid.duckdns.org
  dnsNames:
    - awx.cluster-hybrid.duckdns.org
    - '*awx.cluster-hybrid.duckdns.org'