apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: awx-gateway
  namespace: awx
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 1080
    name: awx-http-gw
    allowedRoutes:
      namespaces:
        from: All
  # - protocol: TLS
  #   port: 1443
  #   name: web-gw-tls
  #   tls:
  #     mode: Passthrough
  #   allowedRoutes:
  #     namespaces:
  #       from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: awx-http-route
  namespace: awx
spec:
  parentRefs:
  - name: awx-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: awx-demo-service
      port: 80


